var pins = 
    [
        ["Bind", "Sova", "Recon_Bolt",  1152, 344, [[835, 176, "vids/BindSovaReconB.mp4", "A-Site Lineup", "Use HUD To Line Up"]], "A-Site Recon Dart"], 
        ["Bind", "Sova", "Recon_Bolt",  695, 248, [[1135, 233, "vids/BindSovaReconA.mp4"]], "B-Site Recon Dart"],
        ['Haven','Viper','Poison_Cloud',779, 127, [[1071, 267,"vids/BindSovaReconA.mp4", 'Back Long Lineup'],[1067,222,"vids/BindSovaReconA.mp4", 'Middle Long Lineup']], 'Heaven Smoke'],
        ['Bind','Brimstone','Incendiary',1223,356, [[1246,476,"vids/Bind/Brimstone/Kikis Youtube Shower Corner Molly.webm", 'Outside Shower Lineup', 'Aim for the middle of leaf, above missing portion.']], 'Shower Boxes Molly'],
        ['Bind','Brimstone','Incendiary',1193,222, [[975,513,'vids/Bind/Brimstone/Thenameistoby Reddit Heaven Molly.webm', 'Attacker Mid-Lobby Lineup'],[1131,603,'vids/Bind/Brimstone/Kikis Youtube Heaven Molly.webm', 'Attacker A Lobby Lineup']], 'Heaven Molly'],
        ['Bind','Brimstone','Incendiary',1018,336, [[1105,573,'vids/Bind/Brimstone/Riival Reddit Brim A Molly.webm', 'Attacker A Lobby Lineup']], 'A Lamp Corner Molly'],
        ['Bind','Brimstone','Incendiary',1165,282, [[1291,534,'vids/Bind/Brimstone/Spikare Reddit Asite Molly.webm', 'A Lobby Lineup']], 'A-Site Boxes Molly'],
        ['Bind','Brimstone','Incendiary',810,269, [[852,527,'vids/Bind/Brimstone/Kikis Youtube B Corner Molly.webm', 'Mid Lineup']], 'B Cubby Molly'],
        ['Bind','Brimstone','Sky_Smoke',1191,313, [[1226,380,'vids/Bind/Brimstone/Spikare Reddit Asite Smokes.webm', 'Shower Lineup']], 'A-Site Smoke'],
        ['Bind','Brimstone','Sky_Smoke',1131,313, [[1226,380,'vids/Bind/Brimstone/Spikare Reddit Asite Smokes.webm', 'Shower Lineup']], 'A-Site Smoke'],
        ['Bind','Brimstone','Sky_Smoke',1191,203, [[1226,380,'vids/Bind/Brimstone/Spikare Reddit Asite Smokes.webm', 'Shower Lineup']], 'A-Site Smoke'],
        ['Haven','Sova','Recon_Bolt',1166,726, [[820,830,'vids/Haven/Sova/Applethauce21 Reddit C Long Recondart.mp4', 'Elevator Lineup', "Aligh bottom left of 'Charge HUD' with Tree."]], 'C Long Recon Dart'],
        ['Split','Sage','Barrier_Orb',1064,124, [[1084,124,'vids/Split/Sage/BulletRisk Twitch Attacker Lobby Heaven Self-Boost.mp4', 'Self Boost']], 'Heaven Peek Self-Boost'],
        ['Split','Sage','Slow_Orb',838,665, [[1088,766,'vids/Split/Sage/Purrplexx B Heaven Slow.mp4', 'Attacker B-Lobby Lineup']], 'B-Site Heaven Slow'],
        ['Split','Sage','Slow_Orb',761,869, [[1136,692,'vids/Split/Sage/Purrplexx B Backsite Slow.mp4', 'Attacker B-Lobby Lineup']], 'Backsite B Slow'],
        ['Split','Sage','Slow_Orb',764,247, [[1084,124,'vids/Split/Sage/Purrplexx A Heaven Slow.mp4', 'Attacker A-Lobby Lineup']], 'A-Site Heaven Slow'],
        ['Split','Sage','Slow_Orb',653,193, [[1084,123,'vids/Split/Sage/Purrplexx A Back Slow.mp4', 'Attacker A-Lobby Lineup']], 'Back A-Site Slow'],
        ['Split','Sage','Slow_Orb',877,315, [[1222,294,'vids/Split/Sage/Purrplexx A Ramp Slow.mp4', 'Attacker A-Lobby Lineup']], 'A Heaven Ramp Slow'],
        ['Bind','Phoenix','Hot_Hands',1221,358, [[1270,413,'vids/Bind/Phoenix/xRiival Reddit Shower Crate Molly.mp4', 'Shower Lineup']], 'Shower Corner Crates Molly'],
        ['Bind','Sage','Slow_Orb',781,402, [[1138,369,'https://v.redd.it/ise16545kmw41/DASH_1080?source=fallback', 'A Site Lineup']], 'Hookah Slow Orb'],
        ['Haven','Raze','Paint_Shells',1035,738, [[858,727,'https://v.redd.it/orlv26s1bur41/DASH_1080?source=fallback.mp4', 'C-Site Lineup']], 'C-Cubby Grenade'],
        ['Bind','Viper','Poison_Cloud',1189,320, [[1112,528,'https://www.youtube.com/embed/z4HR_RAAAVE?start=9', 'A-Lobby Attacker']], 'Front A-Site Smoke'],
        ['Bind','Viper','Toxic_Screen',1120,282, [[1113,529,'https://www.youtube.com/embed/z4HR_RAAAVE?start=26', 'A-Lobby Attacker Lineup']], 'A-Site Wall'],
        ['Haven','Viper','Poison_Cloud',859,702, [[1082,814,'https://v.redd.it/72tee425lrr41/DASH_1080?source=fallback.mp4', 'Attacker C-Lobby Lineup']], 'C-Site Smoke'],
        ['Haven','Brimstone','Incendiary',839,816, [[1169,714,'https://www.youtube.com/embed/9UDd5fYwLpY?start=75', 'Attacker C-Lobby']], 'Elevator Molly'],
        ['Bind','Sova','Recon_Bolt',814,510, [[1101,226,'https://clips.twitch.tv/embed?clip=GenerousNurturingToadBatChest', 'Back A-Site Lineup']], 'Mid Recon Dart'],
        ['Split','Sova','Recon_Bolt',696,824, [[1031,687,'https://www.youtube.com/embed/hnZTfJd8eF0', 'Attacker B-Lobby Lineup']], 'Backsite B Recon Dart'],
        ['Haven','Brimstone','Incendiary',767,128, [[1090,253,'https://v.redd.it/ly47z29mi1s41/DASH_1080?source=fallback.mp4', 'A-Long Lineup']], 'A-Heaven Molly'],
        ['Split','Brimstone','Incendiary',789,70, [[1145,122,'https://www.youtube.com/embed/Yok46-azm2Q?start=25&end=48', 'Attacker A-Lobby Lineup']], 'Default A-Site Plant Molly'],
        ['Haven','Sage','Slow_Orb',1082,461, [[749,436,'vids/Haven/Sage/Flaux Mid Peek Slow.mp4', 'Back B Lineup']], 'Mid Window Slow'],
        ['Haven','Sage','Slow_Orb',755,675, [[1169,816,'vids/Haven/Sage/Flaux Csite Entrance Slow.mp4', 'C-Long Lineup']], 'C-Site Entrance Slow'],
        ['Haven','Sage','Barrier_Orb',820,204, [[758,237,'vids/Haven/Sage/Flaux A-Site Retake Wall.mp4', 'A-Connector Lineup']], 'A-Site Retake Wall'],
        ['Haven','Sage','Slow_Orb',766,129, [[1190,341,'vids/Haven/Sage/Flaux A Heaven Slow.mp4', 'Attacker A-Lobby Lineup']], 'A-Heaven Slow'],
        ['Haven','Sage','Slow_Orb',781,143, [[1211,395,'vids/Haven/Sage/Flaux A Hell Slow.mp4', 'Attacker A-Lobby Lineup']], 'A Hell Slow'],
        ['Haven','Sage','Slow_Orb',1042,220, [[876,84,'vids/Haven/Sage/Flaux A Long Slow.mp4', 'A-Site Lineup']], 'A Long Slow'],
        ['Haven','Sage','Slow_Orb',924,188, [[823,371,'vids/Haven/Sage/Flaux A-Short Slow.mp4', 'A-Site Retake Lineup']], 'A-Short Slow'],
        ['Bind','Sage','Slow_Orb',1029,336, [[1180,595,'https://www.youtube.com/embed/QRysR76_gMA?start=64&end=105', 'Attacker A-Lobby Lineup']], 'A-Short Slow'],
        ['Bind','Sage','Slow_Orb',1091,255, [[1144,527,'https://www.youtube.com/embed/QRysR76_gMA?start=106&end=144?autoplay=1&mute=1', 'A Connector Lineup']], 'A Backsite Entrance Slow'],
        ['Bind','Omen','Dark_Cover',710,345, [[666,380,'https://www.youtube.com/embed/ZsAR_XCFh8s?start=514&end=526', 'B-Long Lineup']], 'B-Site Entrance Smoke'],
        ['Bind','Omen','Dark_Cover',672,298, [[668,380,'https://www.youtube.com/embed/ZsAR_XCFh8s?start=516&=end=526', 'B-Long Lineup']], 'B-Elbow Smoke'],
        ['Bind','Omen','Shrouded_Step',640,295, [[707,362,'https://www.youtube.com/embed/ZsAR_XCFh8s?start=521&end=534', 'B-Entrance Lineup']], 'Sneaky Teleport B-Elbow '],
        ['Bind','Omen','Paranoia',774,429, [[833,436,'https://www.youtube.com/embed/ZsAR_XCFh8s?start=353&end=357', 'Mid Lineup']], 'Back Hookah Blind'],
        ['Split','Sage','Slow_Orb',1068,573, [[893,458,'vids/Split/Sage/Gaia Mid B-Connector Slow.mp4', 'Back Mid Lobby Lineup']], 'Mid B-Connector Slow'],
        ['Split','Sage','Slow_Orb',944,134, [[921,530,'vids/Split/Sage/Gaia Mid A Entrance Slow.mp4', 'Mid Lineup']], 'A Entrance Slow '],
        ['Split','Viper','Toxic_Screen',936,266, [[1174,302,'https://v.redd.it/1k05fapw20s41/DASH_1080?source=fallback.mp4', 'Attacker A-Site Lobby']], 'A-Ramp & A-Heaven Wall'],
        ['Split','Viper','Toxic_Screen',760,249, [[1175,304,'https://v.redd.it/1k05fapw20s41/DASH_1080?source=fallback.mp4', 'Attacker A-Site Lobby']], 'A-Ramp & A-Heaven Wall'],
        ['Bind','Phoenix','Hot_Hands',1021,334, [[1047,495,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=181', 'A-Short Lineup', 'Run Throw']], 'U-Haul Entrance Molly'],
        ['Bind','Phoenix','Blaze',1074,365, [[1097,280,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=330', 'A-Site Lineup', 'Defender utility, slows down pushes.'], [1055,484,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=207', 'A-Site Entrance ', 'Useful for A-Short pushes ']], 'A-Short Wall Push'],
        ['Bind','Phoenix','Hot_Hands',1092,487, [[1058,367,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=269', 'A-Tele Lineup', 'Use At Start of Round ']], 'A-Short Defence Molly'],
        ['Bind','Phoenix','Hot_Hands',1254,394, [[1227,341,'vids/Bind/Phoenix/Xriival Reddit Showers Molly.webm', 'Shower Crates Lineup'], [1177,310,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=301', 'A-Site Crate Corner Lineup', 'Can stop pushes, or ult-point denial']], 'Showers Molly'],
        ['Bind','Phoenix','Blaze',854,410, [[1061,376,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=317', 'A-Tele Lineup', 'Team Utility ']], 'Mid Wall via A-Tele'],
        ['Bind','Phoenix','Hot_Hands',785,436, [[813,498,'https://www.youtube.com/embed/B9raomDyQM4?start=62', 'Safe Mid Lineup', 'Safer than the other two lineups, try let your team know to punish anyone rotating off this molly.'], [876,519,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=376', 'Mid Lineup', 'Riskier lineup, can stop early holds on this spot: however risking getting picked from mid player'],[877,429,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=360', 'B-Tele Box Lineup', 'Safer lineup, angles are at least cleared/peaked, team can punish anyone who rotates off your molly into the clearing']], 'Back Hookah Molly'],
        ['Bind','Phoenix','Hot_Hands',809,267, [[876,427,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=360', 'B-Tele Box', 'Clears out cubby for b-site executes']], 'B-Cubby Molly'],
        ['Bind','Phoenix','Hot_Hands',630,285, [[644,420,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=415', 'B-Tele Entrance Lineup', 'Careful to have the angle into B cleared, as you could be picked from here.']], 'Elbow Molly'],
        ['Bind','Phoenix','Blaze',726,307, [[777,346,'https://www.youtube.com/embed/gd7JU_Ghcv8?start=456', 'Hookah Lineup', 'Good for pushing into site and isolating the elbow and close B-Main players']], 'B-Entrance Wall']


        

    ]
